VIA_ENABLE = yes
DYNAMIC_KEYMAP_ENABLE = yes

TAP_DANCE_ENABLE = yes
REPEAT_KEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
SECURE_ENABLE = yes
SWAP_HANDS_ENABLE = yes
RGB_MATRIX_CUSTOM_USER = yes
